"""align employee schema

Revision ID: 4973d158dd4b
Revises: b6c4b3d4f5e7
Create Date: 2025-11-16 17:11:11.107069

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4973d158dd4b'
down_revision = 'b6c4b3d4f5e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('tareas_asignadas', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('employee', sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index('ix_employee_emailAddress', table_name='employee')
    op.drop_constraint('uq_employee_clerk_id', 'employee', type_='unique')
    op.drop_constraint('uq_employee_email', 'employee', type_='unique')
    op.drop_column('employee', 'firstName')
    op.drop_column('employee', 'role')
    op.drop_column('employee', 'emailAddress')
    op.drop_column('employee', 'accessStatus')
    op.drop_column('employee', 'lastName')
    op.drop_column('employee', 'id')
    op.drop_column('employee', 'updatedAt')
    op.drop_column('employee', 'imageUrl')
    op.drop_column('employee', 'fullName')
    op.drop_column('employee', 'organizationIds')
    op.drop_column('employee', 'createdAt')
    op.drop_column('service', 'description')
    op.drop_column('service', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('service', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('employee', sa.Column('organizationIds', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
    op.add_column('employee', sa.Column('fullName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee', sa.Column('imageUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('employee', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('employee', sa.Column('lastName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee', sa.Column('accessStatus', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('employee', sa.Column('emailAddress', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('employee', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('employee', sa.Column('firstName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('uq_employee_email', 'employee', ['emailAddress'])
    op.create_unique_constraint('uq_employee_clerk_id', 'employee', ['clerkId'])
    op.create_index('ix_employee_emailAddress', 'employee', ['emailAddress'], unique=False)
    op.drop_column('employee', 'estado')
    op.drop_column('employee', 'tareas_asignadas')
    # ### end Alembic commands ###
