"""database_v1

Revision ID: 66ca29618169
Revises: 
Create Date: 2025-11-16 18:20:30.750192

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '66ca29618169'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banquet_table',
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('organizationIds', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clerkId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emailAddress', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('firstName', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lastName', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fullName', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('imageUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accessStatus', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerkId', name='uq_employee_clerk_id'),
    sa.UniqueConstraint('emailAddress', name='uq_employee_email')
    )
    op.create_index(op.f('ix_employee_clerkId'), 'employee', ['clerkId'], unique=False)
    op.create_index(op.f('ix_employee_emailAddress'), 'employee', ['emailAddress'], unique=False)
    op.create_table('service',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('eiltRate', sa.Float(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banquet_seat',
    sa.Column('seatNumber', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tableId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tableId'], ['banquet_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('startTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accountId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seatId', sa.Integer(), nullable=True),
    sa.Column('serviceId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('isRedeemed', sa.Boolean(), nullable=False),
    sa.Column('isRated', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['seatId'], ['banquet_seat.id'], ),
    sa.ForeignKeyConstraint(['serviceId'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('banquet_seat')
    op.drop_table('service')
    op.drop_index(op.f('ix_employee_emailAddress'), table_name='employee')
    op.drop_index(op.f('ix_employee_clerkId'), table_name='employee')
    op.drop_table('employee')
    op.drop_table('banquet_table')
    # ### end Alembic commands ###
