"""v1

Revision ID: 972bb321cd9e
Revises: 
Create Date: 2025-11-24 22:38:27.683012

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '972bb321cd9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banquet_table',
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('tareas_asignadas', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('clerkId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('clerkId')
    )
    op.create_index(op.f('ix_employee_clerkId'), 'employee', ['clerkId'], unique=False)
    op.create_table('item',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('private_venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('eiltRate', sa.Float(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spirit_type',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kanji', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dangerScore', sa.Integer(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banquet_seat',
    sa.Column('seatNumber', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tableId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tableId'], ['banquet_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spirit',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('typeId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['typeId'], ['spirit_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_relation',
    sa.Column('relation', sa.String(), nullable=False),
    sa.Column('source_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_type_id'], ['spirit_type.id'], ),
    sa.ForeignKeyConstraint(['target_type_id'], ['spirit_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_intake',
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.Column('seatId', sa.Integer(), nullable=True),
    sa.Column('serviceId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['itemId'], ['item.id'], ),
    sa.ForeignKeyConstraint(['seatId'], ['banquet_seat.id'], ),
    sa.ForeignKeyConstraint(['serviceId'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venue_account',
    sa.Column('startTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spiritId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('privateVenueId', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['privateVenueId'], ['private_venue.id'], ),
    sa.ForeignKeyConstraint(['spiritId'], ['spirit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('startTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accountId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seatId', sa.Integer(), nullable=True),
    sa.Column('serviceId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('isRedeemed', sa.Boolean(), nullable=False),
    sa.Column('isRated', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['accountId'], ['venue_account.id'], ),
    sa.ForeignKeyConstraint(['seatId'], ['banquet_seat.id'], ),
    sa.ForeignKeyConstraint(['serviceId'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('venue_account')
    op.drop_table('item_intake')
    op.drop_table('type_relation')
    op.drop_table('spirit')
    op.drop_table('banquet_seat')
    op.drop_table('spirit_type')
    op.drop_table('service')
    op.drop_table('private_venue')
    op.drop_table('item')
    op.drop_index(op.f('ix_employee_clerkId'), table_name='employee')
    op.drop_table('employee')
    op.drop_table('banquet_table')
    # ### end Alembic commands ###
